---
title: "actionbuttons"
output: html_document
---

```{r}
library(shiny)

ui <- fluidPage(
  actionButton("ohno", label = "Oh no!"),
    textOutput("Diabetes"),
    textOutput("Leukemia"),
    textOutput("Oral cancer"),
    textOutput("Pancreatic cancer"),
    textOutput("Heart disease"),
    textOutput("Kidney disease"))

server <- function(input, output){
  
   #  Use a list of reactive values
  x <- actionbuttons$ResponseA
  rv <- reactiveValues(x=0)

  # Will update text output when rv$x is updated
  observe({
    output$Diabgetes <- renderText({ rv$x })
  })}


shinyApp(ui, server)
```
```{r}
library(shiny)
library(dplyr)

ui <- fluidPage(
  actionButton("ohno", label = "Oh no!"),
   verbatimTextOutput("problems"))


server <- function(input, output){
  
  thingsToSay <- c("Diabetes", "Leukemia", "Oral cancer", "Pancreatic cancer", "Heart disease", "Kidney disease")
  
  output$problems <- renderText({
    if (input$ohno > 0 && input$ohno < 7) {
thingsToSay[input$ohno]    
     } else {""}
  })
}

shinyApp(ui, server)
```

```{r}
library(shiny)
library(dplyr)

ui <- fluidPage(
  actionButton("help", label = "Help!"),
   verbatimTextOutput("solutions"))


server <- function(input, output){
  
  thingsToSayHere <- c("Brush twice a day for two minutes with fluoridated toothpaste", "Floss daily to remove plaque that your toothbrush can't reach", "Maintain a healthy diet to obtain the nutrients that prevent gum disease", "Avoid cigarettes and smokeless tobacco", "Visit the dentist regularly for cleanings and exams", "Keep your dentist informed of your medical history and any health developments even if they seem unrelated to your oral health")
  
  output$solutions <- renderText({
    if (input$help > 0 && input$help < 7) {
thingsToSayHere[input$help]    
     } else {""}
  })
}

shinyApp(ui, server)
```

