---
title: "countryvalues"
runtime: shiny
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(ggplot2)
library(shiny)
library(dplyr)
library(tidyr)
countryplot <- read.csv("newtable1_5.csv")
```

```{r}
ggplot(countryplot, aes(X2012,X2014, color=LocationDesc)) + xlab("2012_values") + ylab("2014_values") + geom_point()
```
```{r}
inputPanel(
  selectInput("LocationDesc5", label = "State", choices = unique(countryplot$LocationDesc))
)
```
```{r}
renderPlot({
  countryplot%>% 
  filter(LocationDesc == input$LocationDesc5) %>% 
  ggplot(aes(X2012, X2014, color=LocationDesc)) +xlab("2012_values") + ylab("2014_values")+geom_point()
})
```
          this goes into the ui                 tabPanel("2012vs.2014",
                           box("Looking at difference between 2012 and 2014 values by State:",
                               inputPanel(
                              selectInput("LocationDesc5", label = "State", choices = unique(countryplot$Location Desc)
                                 plotOutput("countryplot1"))),
                                 
                                 
                                 
 this goes into server                                
output$countryplot1 <- renderPlot({
    countryplot%>% 
      filter(LocationDesc == input$LocationDesc5) %>% 
      ggplot(aes(X2012, X2014, color=LocationDesc)) +xlab("2012_values") + ylab("2014_values")+geom_point()})