---
title: "Untitled"
output: html_document
---
```{r}

library(ggplot2)

ui <- fluidPage(
    fluidRow(
        column(width = 12,
               plotOutput("statewiderace", height = 350, hover = hoverOpts(id ="plot_hover"))
        )
    ),
    fluidRow(
        column(width = 5,
               verbatimTextOutput("hover_info")
        )
    )
)

server <- function(input, output) {


    output$statewiderace <- renderPlot({
        race %>%
        ggplot(aes(Female, Male, color = LocationAbbr) + geom_point()  + guides(color = guide_legend(title = "State:")))})

    output$hover_info <- renderPrint({
        if(!is.null(input$plot_hover)){
            hover=input$plot_hover
            dist=sqrt((hover$x-genderB$Female)^2+(hover$y-genderB$Male)^2)
            cat("State:")
            if(min(dist) < 3)
                genderB$LocationAbbr[which.min(dist)]
        }


    })
}
shinyApp(ui, server)
```

```{r}
  
  output$hover_info <- renderPrint({
      genderB %>% 
        ggvis(x = Female, y = Male, size.hover := 200) %>%
      layer_points()})

```

```{r}
library(shiny)
library(ggplot2)

ui <- fluidPage(

  tags$head(tags$style({
      position: absolute;
      width: 300;
      z-index: 100;
     })),
  
  tags$script(
    (document).ready(function(){
    ("genderB").mousemove(function(e){ 
        
        $("my_tooltip").show();         
        $("my_tooltip").css({             
          top: (e.pageY + 5) + "px",             
          left: (e.pageX + 5) + "px"         
        });     
      });     
    });
  ),

  selectInput("var_y", "Y-Axis", choices = names(mtcars), selected = "disp"),
  plotOutput("plot1", hover = hoverOpts(id = "plot_hover", delay = 0)),
  uiOutput("my_tooltip")
)

server <- function(input, output) {

  data <- reactive({
    mtcars
  })

  output$plot1 <- renderPlot({
    req(input$var_y)
    ggplot(data(), aes_string("mpg", input$var_y)) + 
      geom_point(aes(color = factor(cyl)))
  })

  output$my_tooltip <- renderUI({
    hover <- input$plot_hover 
    y <- nearPoints(data(), input$plot_hover)[ ,c("mpg", input$var_y)]
    req(nrow(y) != 0)
    verbatimTextOutput("vals")
  })

  output$vals <- renderPrint({
    hover <- input$plot_hover 
    y <- nearPoints(data(), input$plot_hover)[ , c("mpg", input$var_y)]
    # y <- nearPoints(data(), input$plot_hover)["wt"]
    req(nrow(y) != 0)
    # y is a data frame and you can freely edit content of the tooltip 
    # with "paste" function 
    y
  })
}
shinyApp(ui = ui, server = server)
```

#trying to make race graph
```{r}
library(shiny)
library(ggplot2)

ui <- fluidPage(
  selectInput("race", label = "Race", choices = unique(race2$Break_Out), selected = "disp"),
  plotOutput("statewiderace")
)

server <- function(input, output) {

  data <- reactive({
    race2
  })

  output$statewiderace <- renderPlot({
    req(input$race)
    ggplot(race2, aes(LocationAbbr, input$race)) + xlab("State") + ylab("Percent") + geom_bar(stat = "identity") + theme(axis.text.x = element_text(angle = 60, hjust = 1))
  })
}
shinyApp(ui = ui, server = server)
```

```{r}
box("Countrywide comparison of gender data:",
                        plotOutput("statewidegender", hover = hoverOpts(id = "plot_hover", delay = 0)),
                        uiOutput("hover_info"))),


```

#another attempt at race graph

```{r}
library(shiny)
library(ggplot2)

ui <- fluidPage(
  selectInput("race", label = "Race", choices = c("Black","White", "Hispanic", "MultiRacial", "Other"), selected = "disp"),
  plotOutput("statewiderace")
)

server <- function(input, output) {

  data <- reactive({
    raceB
  })

  output$statewiderace <- renderPlot({
    req(input$race)
    ggplot(raceB, aes(LocationAbbr, Black)) + xlab("State") + ylab("Percent") + geom_bar(stat = "identity") + theme(axis.text.x = element_text(angle = 60, hjust = 1))
  })
}
shinyApp(ui = ui, server = server)
```

```{r}
library(shiny)
library(ggplot2)

ui <- fluidPage(
  selectInput("race", label = h3("Race:"), 
    choices = list("Black" = raceB$Black, "White" = raceB$White, "Hispanic" = raceB$Hispanic, "MultiRacial" = raceB$MultiRacial, "Other" = raceB$Other),
    selected = NULL,
    multiple = FALSE,
    selectize = FALSE),
  
  hr(),
  fluidRow(column(3, verbatimTextOutput("value")))
  
)

server <- function(input, output) {
  
  output$statewiderace <- renderPlot({
    req(input$race)
    ggplot(raceB, aes(LocationAbbr, Black)) + xlab("State") + ylab("Percent") + geom_bar(stat = "identity") + theme(axis.text.x = element_text(angle = 60, hjust = 1))
  })
}

shinyApp(ui = ui, server = server)
```



