---
title: "income graphs"
output: html_document
---

```{r}
library(shiny)
library(dplyr)
library(ggplot2)
```
```{r}
income <- filter(newtable, Break_Out_Category == "Income", Indicator == "Adults aged 18+ who have visited a dentist or dental clinic in the past year", Response == "Yes", Year == "2014", LocationDesc != "Guam", LocationDesc != "Puerto Rico")
```

```{r}
ggplot(income, aes(Break_Out, Data_Value)) + xlab("Income") + ylab("Percent") + geom_bar(stat = "identity")
```

```{r}
library(shiny)
library(ggplot2)

ui <- fluidPage(
  selectInput("income", label = "Income", choices = unique(income$Break_Out), selected = "disp"),
  plotOutput("statewideincome")
)

server <- function(input, output) {

  data <- reactive({
    income
  })

  output$statewideincome <- renderPlot({
    income %>%
      filter(Break_Out == input$income) %>%
    ggplot(aes(LocationAbbr, Data_Value)) + xlab("State") + ylab("Percent") + geom_bar(stat = "identity") + theme(axis.text.x = element_text(angle = 60, hjust = 1))
  })
}
shinyApp(ui = ui, server = server)
```
```{r}
library(shiny)
library(ggplot2)

ui <- fluidPage(
  selectInput("education", label = "Education", choices = unique(education2$Break_Out), selected = "disp"),
  plotOutput("countrywideeducation")
)

server <- function(input, output) {

  output$countrywideeducation <- renderPlot({
    education2 %>%
      filter(Break_Out == input$education) %>%
    ggplot(aes(LocationAbbr, Data_Value)) + xlab("State") + ylab("Percent") + geom_bar(stat = "identity") + theme(axis.text.x = element_text(angle = 60, hjust = 1))
  })
}
shinyApp(ui = ui, server = server)
```

