---
title: "webpage layout"
output: html_document
---

```{r}
library(shiny)
install.packages("shinydashboard")
library(shinydashboard)
```

```{r}
dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody())

ui <- dashboardPage(
  
      dashboardHeader(title = "Oral Health Trends"),
  
      dashboardSidebar( 
        sidebarMenu(
          menuItem("Home", tabName = "Home", icon = icon("Home")),
          menuItem("Age 18+", tabName = "age18", icon = icon("Age 18+")))),
  
      dashboardBody(
        tabItems(
          tabItem(tabName = "Home",
            fluidPage(
              titlePanel("Welcome to our page!"),
              mainPanel("info about our page and why its important"))),
        
          tabItem(tabName = "age18",
              titlePanel("Adults aged 18+ who have visited a dentist in the past year")))))

server <- function(input, output) { }

shinyApp(ui, server)
```
```{r}
dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody())

ui <- dashboardPage(
  
      dashboardHeader(title = "Oral Health Trends"),
  
      dashboardSidebar( 
        sidebarMenu(
          menuItem("Home", tabName = "Home", icon = icon("Home")),
          menuItem("Age 18+", tabName = "age18", icon = icon("Age 18+")),
          menuItem("Data Source", tabName = "datasource", icon = icon("Data Source")))),
  
      dashboardBody(
        tabItems(
          tabItem(tabName = "Home",
            fluidPage(
              titlePanel("Welcome to our page!"),
              mainPanel("info about our page and why its important"))),
        
          tabItem(tabName = "age18",
              titlePanel("Adults aged 18+ who have visited a dentist in the past year"),
              mainPanel(
                tabsetPanel(
                  tabPanel("Gender",
                    inputPanel(selectInput("LocationDesc", label = "State", choices = unique(gender$LocationDesc)))),
                  tabPanel("Age"),
                  tabPanel("Race"),
                  tabPanel("Income"),
                  tabPanel("Education")))),
          
          tabItem(tabName = "datasource",
              titlePanel("Data Source")))))

server <- {renderPlot({
            gender %>%
              filter(LocationDesc == input$LocationDesc) %>%
              ggplot(aes(Break_Out, Data_Value)) + geom_bar(stat = "identity")})}

shinyApp(ui, server)
```

